version: '3.8'

networks:
  main:
    driver: bridge
  
volumes:
  minio_data:
    driver: local

services:
  database:
    image: postgres
    container_name: athena_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - main
  
  storage:
    image: minio/minio
    container_name: athena_storage
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - main
    volumes:
      - minio_data:/data